# -- [STAGE - 1] -- Dependencias.
FROM node:21-alpine3.19 AS deps
WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json* ./
COPY pnpm-lock.json* ./
COPY . .

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "start:dev"]